name: example
description: A sample application that uses crossword_generator.
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  crossword_generator: 
    path: ../../crossword_generator
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
